//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportIt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EUReported
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EUReported()
        {
            this.ReportedSrcUrls = new HashSet<ReportedSrcUrl>();
            this.ReportedLinkUrls = new HashSet<ReportedLinkUrl>();
            this.ReportedSelectedTexts = new HashSet<ReportedSelectedText>();
        }
    
        public string PageUrlHash { get; set; }
        public string PageUrl { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public bool Processed { get; set; }
        public int Count { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportedSrcUrl> ReportedSrcUrls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportedLinkUrl> ReportedLinkUrls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportedSelectedText> ReportedSelectedTexts { get; set; }
    }
}
