//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportIt.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ReportItEntities : DbContext
    {
        public ReportItEntities()
            : base("name=ReportItEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EUReported> EUReporteds { get; set; }
        public virtual DbSet<LinkUrl> LinkUrls { get; set; }
        public virtual DbSet<ReportedLinkUrl> ReportedLinkUrls { get; set; }
        public virtual DbSet<ReportedSelectedText> ReportedSelectedTexts { get; set; }
        public virtual DbSet<ReportedSrcUrl> ReportedSrcUrls { get; set; }
        public virtual DbSet<SelectionText> SelectionTexts { get; set; }
        public virtual DbSet<SrcUrl> SrcUrls { get; set; }
    }
}
